### ISSUE TITLE
Conflict with libWrapper

### ISSUE THREAD

**Issue by JamzTheMan** [jegasus/scene-clicker#1]
Having this module activated with libWrapper prevents Actor sheets from opening from the sidebar.

Not sure if this is a Scene Clicker issue or libWrapper but I narrowed down the issue only persists if I have both activated.

**Comment by jegasus** [comment]
Hi there, thanks for reporting the error!
I just tried replicating the issue on my side and couldn't get the bug to happen. Here's the specs of my current run:

- FoundryVTT 0.7.9
- Scene Clicker 0.0.6
- libWrapper 1.1.4.0

libWrapper just had a bit of a hiccup between yesterday and today (which they have already fixed). Can you try uninstalling and reinstalling it to see if that works?

If not, send me the details (versions) of your current setup.

Thanks again!

**Comment by jegasus** [comment]
Solved by libWrapper's [Issue #11](https://github.com/ruipin/fvtt-lib-wrapper/issues/11)
