### ISSUE TITLE
Journal Entries

### ISSUE THREAD

**Issue by GuineaThePig** [jegasus/scene-clicker#2]
Would be awesome if this worked on journal links as well, so players could move around linked scenes instead of being able to change the settings

**Comment by jegasus** [comment]
This is a fantastic idea! I'll work to add this as a new feature. Thanks for the idea!

**Comment by jegasus** [comment]
This issue has been addressed and the new feature was added in [Release 0.0.7](https://github.com/jegasus/scene-clicker/releases/tag/0.0.7)
