### ISSUE TITLE
Suggestion: Hotkey to Activate Scene instead

### ISSUE THREAD

**Issue by Hebelios** [jegasus/scene-clicker#3]
I would humbly request a kind of hotkey to Activate a scene with a quick-link rather than vieving it.
(e.g. CTRL-Click to automatically Activate the Scene, rather than viewing it.

EDIT: Might I also suggest adding ALT-Click (or something along the likes) to Configure instead? Currently I always disable the module to quickly edit lots of scenes in quick succession, holding ALT when clicking them would allow me to keep the module active.)

**Comment by jegasus** [comment]
Yes, I really like the idea! I was already going to implement the Alt+Click for the Config Sheet, but hadn't thought of Ctrl+Click to activate. Thanks for the suggestion!
I'm currently working on another Foundry-related project, but I will implement this improvement in Scene-Clicker when I find a little break!
Thanks again for the great suggestion!

**Comment by jegasus** [comment]
It took a while to get to this issue, but I've finally added the new functionality! 
Now you can use Ctrl+Click to Activate a scene and Alt+Click to render the config sheet.
Enjoy!!!
