### ISSUE TITLE
Error in console when logging in

### ISSUE THREAD

**Issue by uniwars** [jegasus/scene-clicker#5]
Hello, I get this error when logging in with scene clicker 👍 
![image](https://user-images.githubusercontent.com/65986545/127739569-390cb651-6ba1-4b42-ab92-7c08778221e9.png)

with ony scene clicker and libwrapper activated

**Comment by ArtheniusRPG** [comment]
Same error for me, I also have lib-wrapper activated, would be awesome to solve this :)

**Comment by jegasus** [comment]
This was due to the module not being compatible with version 0.8.x. A kind soul did most of the work and updated the module - this should be fixed. Please re-open the issue if this persists.
