### ISSUE TITLE
A warning message but works

### ISSUE THREAD

**Issue by Gabryel666** [jegasus/scene-clicker#8]
Hello,

The module seems to work correctly but when loading the game I get this error message :

<img width="575" alt="image" src="https://user-images.githubusercontent.com/65908230/147508000-9349c216-907c-45b0-878b-196cb1cc49d8.png">

And in the console :

<img width="397" alt="image" src="https://user-images.githubusercontent.com/65908230/147507954-daab95a5-4d05-465d-ba44-9c2de9d5ea38.png">

Foundryvtt V9.238

Thx for your work, ++

**Comment by jegasus** [comment]
I've just released a new version of the module that makes it work for Foundry v9! Please let me know if the issues persist =)
