### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [jegasus/scene-clicker#9]
**Submitted By**: test
**Feedback Type**: Bug
 
**Core:** 9.242
**System:** dnd5e v1.5.6
**Module Version:** scene-clicker v0.0.10
**Dependency Version:** libWrapper v1.11.2.0
 
**Description**:
testing the "bug reporter"<details>
<summary>Module Settings</summary>

```js

```
</details>
<details>
<summary>Active Modules</summary>

bug-reporter--v1.3.2;
lib-wrapper--v1.11.2.0;
scene-clicker--v0.0.10;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by jegasus** [comment]
"Bug Reporter" works great! Closing the issue.
